### ISSUE TITLE
PHP warning: count() for PHP 7

### ISSUE THREAD

**Issue by toelva** [Jako/minifyRegistered#1]
Hi Jako,

PHP 7 creates many entries in the error log by calling count () on non-countable variables:

`[2019-09-23 13:42:06] (ERROR @ /core/cache/includes/elements/modplugin/45.include.cache.php : 162) PHP warning: count(): Parameter must be an array or an object that implements Countable`

From line 162ff instead of
`if (count ($ registeredScripts ['head_cssexternal']) {`
  should be called??
`if (is_array ($ registeredScripts ['head_cssexternal']) && count ($ registeredScripts ['head_cssexternal']) {`

Greatings Iris

**Comment by Jako** [comment]
Please try the upcoming 0.3.3 version: https://github.com/Jako/minifyRegistered-revo/raw/0.3.3-rc1/_packages/minifyregistered-0.3.3-rc1.transport.zip
